version: '3.9'
services:
  postgres:
    image: postgres:15.7
    container_name: postgresql
    volumes:
      - ./scripts/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    environment:
      - POSTGRES_USER=api
      - POSTGRES_PASSWORD=spring@123
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U api -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5