
CREATE DATABASE "DKR-TAREFAS-DB01";
GRANT ALL PRIVILEGES ON DATABASE "DKR-TAREFAS-DB01" TO "api";

CREATE DATABASE "DKR-TESTE-TAREFAS-DB02";
GRANT ALL PRIVILEGES ON DATABASE "DKR-TESTE-TAREFAS-DB02" TO "api";